-- ChartWise: Add unique username constraint (case-insensitive)
-- Run this in Supabase SQL Editor if you already created the leaderboard table
-- See supabase-leaderboard-case-insensitive.sql for case-insensitive migration
